version: '3'

services:
  mysqlsrv:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "o97bcl3r"
      MYSQL_DATABASE: "testedb"
    ports:
      - "3306:3306"
    volumes:
      - D:\db\mysql:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8099:8080
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge